### ISSUE TITLE
Go to variable definition does not show up in the contextual menu

### ISSUE THREAD

**Issue by bobrocke** [Monnoroch/ColorHighlighter#236] opened 2015-08-06 19:30 UTC
Mac OS, Sublime Text v3 3095

**Comment by Monnoroch** [comment] 2015-08-20 19:57
Should be fixed in brand new V7.
Reopen, if not (I don't have macs).

**Closed by Monnoroch** 2015-08-20 19:57 UTC

**Comment by bobrocke** [comment] 2015-08-23 22:08
It does show now, but it doesn't do anything. At least not in my .scss file.

**Comment by Monnoroch** [comment] 2015-08-24 08:48
Could you provide the minimal example to test this? I can't reproduce the bug myself.
