### ISSUE TITLE
Unable to get ColorHighlighter to work

### ISSUE THREAD

**Issue by catdragon** [Monnoroch/ColorHighlighter#167] opened 2014-11-14 17:23 UTC
I am sure i am missing something here, but i can't get the plugin to work.  is there any known issues having to do with other packages or settings that could stop ColorHighlighter from working?

Heck, i just want to make sure it installed correctly.  How can i do that?

**Comment by revolt666** [comment] 2015-01-18 10:54
I have the same problem and the error message is `UnicodeEncodeError: 'ascii' codec can't encode character u'\u2013' in position 2741: ordinal not in range(128)`. The problem is that the character U+2013 is `–` ([en dash](http://www.fileformat.info/info/unicode/char/2013/index.htm)) but I can't find it in my _css_ file.

**Comment by atsea** [comment] 2015-04-01 14:02
Mine would work, then not work. I updated my user settings with @Monnoroch 's and it is working again.
Latest build 3083

**Comment by tildebyte** [comment] 2015-06-26 15:14
@GrantSP: Are you on Windows? You've almost certainly got Windows' `convert` command in the path ahead of Imagemagick's `convert` (you do have Imagemagick installed, right?). This happened to me on a new system recently. I forgot that *I* didn't have IM installed :)

**Comment by cipinistor** [comment] 2015-07-20 08:36
I had the same issue. After I disabled BracketHighlighter package, this works now.

**Comment by Monnoroch** [comment] 2015-08-20 20:08
Should be fixed in V7.

**Closed by Monnoroch** 2015-08-20 20:08 UTC
