### ISSUE TITLE
For whom confused that found CH cannot read named color!

### ISSUE THREAD

**Issue by sbwfnyiiiu** [Monnoroch/ColorHighlighter#435] opened 2018-01-11 12:20 UTC
When I use color name(e.g. red, green,blue etc), the Color Highlighter on Windows and Ubuntu not working(hex,rgb format works fine).On macOS everything works fine. 
![image](https://user-images.githubusercontent.com/10709194/34825297-dd1138a0-f70c-11e7-8cb4-8b50d7d25b36.png)

Windows 10 not working
Sublime text 3  3143
-------------------------
![image](https://user-images.githubusercontent.com/10709194/34828151-8e11f932-f717-11e7-8196-ca874aa758cf.png)
Ubuntu 17 not working
Sublime text 3  3143
-------------------------

I got the link:  https://github.com/Monnoroch/ColorHighlighter/issues/377
Please wait, like the author said, "It will be implemented asap".

Looks like it  works only on macOS now, looking forward to other OS platform.

**Comment by Monnoroch** [comment] 2018-02-09 19:11
Duplicate of #381.

**Closed by Monnoroch** 2018-02-09 19:11 UTC
