### ISSUE TITLE
It color the id's names

### ISSUE THREAD

**Issue by Erimen** [Monnoroch/ColorHighlighter#405] opened 2017-10-23 11:57 UTC
Hello,

I found that the plugin is coloring in the selector.
If a give to a div this id "affiche", in my css file I need to use "#affiche" and the three first letters are in blue.
It isn't a real problem but if it's possible to avoid the coloring of the selector, it would be good :)

Thanks

**Comment by Monnoroch** [comment] 2017-10-23 12:37
Duplicate of #396.

**Closed by Monnoroch** 2017-10-23 12:37 UTC
