### ISSUE TITLE
Disable variable highlighting when declaring it.

### ISSUE THREAD

**Issue by dzift** [Monnoroch/ColorHighlighter#346] opened 2017-02-05 11:02 UTC
e.g. in SASS

![colors](https://cloud.githubusercontent.com/assets/21025134/22625577/ec623922-eb9a-11e6-8e9b-753dacb1148c.png)

Which is really annoying. Is there a way to turn this off?

**Comment by Stephanyan** [comment] 2017-04-27 23:11
If you have found a solution, I'm interested about it too...

**Comment by dzift** [comment] 2017-05-01 08:07
Yeah, I went back to the slower but much more pleasant to work with Atom.

**Comment by Stephanyan** [comment] 2017-05-01 10:23
Thank you for your reply. That's a very good option.

**Comment by davmillar** [comment] 2017-06-02 18:51
@dzift  @Stephanyan can you please share what OS and OS version you're using, as well as what version of ST? I'm unable to reproduce that behavior on Fedora 25 with ST3 build 3126:
![image](https://cloud.githubusercontent.com/assets/576958/26740280/828c56b6-479a-11e7-9ec2-87db7be33bc1.png)

**Comment by dzift** [comment] 2017-06-03 13:43
I was on Linux Mint 18.1 Cinammon running ST3 3126.

**Comment by petitJAM** [comment] 2017-08-17 16:49
I also see this problem on Ubuntu 16.04

**Comment by dzift** [comment] 2017-10-04 09:03
Btw @davmillar you replicated the issue in that pic. 

The issue is that when declaring the variable, the variable name should not be highlighted.

**Comment by Monnoroch** [comment] 2017-10-04 09:43
Guys, https://github.com/Monnoroch/ColorHighlighter#variables-highlighting. I'm closing this for the time being.

**Closed by Monnoroch** 2017-10-04 09:43 UTC
