### ISSUE TITLE
 #ID colored in .sass

### ISSUE THREAD

**Issue by Elisseii** [Monnoroch/ColorHighlighter#403] opened 2017-10-18 20:24 UTC
![screenshot_1](https://user-images.githubusercontent.com/19194085/31740793-ff018f22-b45a-11e7-8392-dfe6446f2c20.png)

**Comment by Monnoroch** [comment] 2017-10-18 20:29
Duplicate of #396.

**Closed by Monnoroch** 2017-10-18 20:29 UTC
