### ISSUE TITLE
Conversion not working

### ISSUE THREAD

**Issue by jCrip** [Monnoroch/ColorHighlighter#257] opened 2015-08-28 19:09 UTC
Still not working. same issue here

The console will output:
ChReplaceColor: {'words': "((37, 44), 'hsl()', '#1ed760FF')"}

and nothing happens.

OSX Yosemite, ST3 3095

**Comment by Monnoroch** [comment] 2015-08-31 11:24
Duplicate of https://github.com/Monnoroch/ColorHighlighter/issues/248.

**Closed by Monnoroch** 2015-08-31 11:24 UTC
