### ISSUE TITLE
Doesn't recognize color in words like "yellow"

### ISSUE THREAD

**Issue by ZYinMD** [Monnoroch/ColorHighlighter#419] opened 2017-11-17 22:01 UTC
Hex and RGB colors are working fine for me, but colors in words doesn't work. How can I fix it? Thanks!
![image](https://user-images.githubusercontent.com/32368482/32970896-d7b7edc4-cbb8-11e7-8877-7092a6dae57a.png)

**Comment by allisonplus** [comment] 2017-11-18 15:18
I'm also experiencing this issue.
![screen shot 2017-11-18 at 10 17 18 am](https://user-images.githubusercontent.com/10225971/32981927-c2c405b0-cc49-11e7-8acc-b1dcd4191918.jpg)

**Comment by c4t3rpilL4r** [comment] 2017-11-21 15:27
![untitled](https://user-images.githubusercontent.com/32305152/33080620-8b78001c-cf13-11e7-87c9-d69f03cefa83.png)
Same here. I hope this can be addressed asap.

**Comment by claudiney** [comment] 2017-11-24 17:59
The same thing happens to me.

**Comment by H2SO4JB** [comment] 2017-11-27 16:31
Same here...

**Comment by Monnoroch** [comment] 2017-11-27 16:33
Please read the readme before creating issues. 

Duplicate of #381.

**Closed by Monnoroch** 2017-11-27 16:33 UTC

**Comment by WillsXiao** [comment] 2018-01-03 09:01
Same here....
