### ISSUE TITLE
not working with normal color words 

### ISSUE THREAD

**Issue by mIcHyAmRaNe** [Monnoroch/ColorHighlighter#440] opened 2018-02-09 19:03 UTC
Hello i'm using the latest version of sublime text 3 (build 3157)

i installed Color Highlighter package and it's working with rgb color code and hex color code: 
```
   background-color: rgb(66, 134, 244);  //... working
   background-color: #42b983;   //... working
```
but when i use simple color words it's not working: 
```
   background-color: blue;  //... not working
```

tested in different file extensions ... and always same problem 😞

![screenshot](https://i.imgur.com/GulUPAf.png)

**Comment by Monnoroch** [comment] 2018-02-09 19:10
Duplicate of #381.

**Closed as completed by Monnoroch** 2018-02-09 19:10 UTC
