### ISSUE TITLE
Interference with other plugins custom veiws

### ISSUE THREAD

**Issue by alextegelid** [Monnoroch/ColorHighlighter#256] opened 2015-08-28 07:46 UTC
I've noticed [some wierd behaviour with GitSavvy](https://github.com/divmain/GitSavvy/issues/230) lately and after some digging it seems Color Highlighter is hijacking GitSavvys views (see link above).

Is there any way to get Color Highlighter to ignore custom views? This issue started occurring about two weeks ago. Let me know if/when you want me to test something!

**Comment by younes0** [comment] 2015-08-28 07:50
Color Highlighter also disables MarkdownEditing color scheme <https://github.com/SublimeText-Markdown/MarkdownEditing/issues/300>

**Comment by alextegelid** [comment] 2015-08-28 18:35
An relatively quick fix might be adding a setting to disable CH in specific views. Something along the lines of this:
```
{
    "disabled_views": ["the other plugin's view", "some other view"]
}
```
And all the views containing those words would be ignored. Even better if it supported regular expressions to be able to specify wether the view/tab starts or ends with specific words for example. In my case I would like to ignore views that starts with `DIFF:` (among others) and in #244 it would have to end with `.TODO`. (ping @Chris-May)

How does this sound? This might be a good solution until you're able to disable CH for other plugins custom views.

**Comment by vongoh** [comment] 2015-08-28 23:57
I also had this problem with Color Highlighter disabling my custom color scheme in Markdown Editing.   I had to disable CH to get my markdown scheme back.

**Comment by alextegelid** [comment] 2015-08-29 08:09
@younes0 @vongoh Have you also noticed this in the past 1-2 weeks or so?

**Comment by younes0** [comment] 2015-08-29 08:12
Yes, like 3 days ago
Le 29 août 2015 10:09 AM, "Alexander Tegelid" <notifications@github.com> a
écrit :

**Comment by Monnoroch** [comment] 2015-08-31 11:22
Duplicate of https://github.com/Monnoroch/ColorHighlighter/issues/249.

**Closed by Monnoroch** 2015-08-31 11:22 UTC

**Comment by alextegelid** [comment] 2015-08-31 12:36
This is ok of course. Please keep the comments in this thread in mind when you look into #249

**Comment by vongoh** [comment] 2015-08-31 17:39
Yes,  it started happening about three days ago just before I opened this issue -- [SublimeText-Markdown/MarkdownEditing#300](http://bit.ly/1iePD91).
